/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Lulim
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jAgregarAlumno = new javax.swing.JMenuItem();
        jBuscarAlumno = new javax.swing.JMenuItem();
        jModificarAlumno = new javax.swing.JMenuItem();
        jAltaLogica = new javax.swing.JMenuItem();
        jBajaLogica = new javax.swing.JMenuItem();
        jListadoAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAgregarMaterias = new javax.swing.JMenuItem();
        jBuscarMaterias = new javax.swing.JMenuItem();
        jModificarMaterias = new javax.swing.JMenuItem();
        jMAltaLogica = new javax.swing.JMenuItem();
        jMBajaLogica = new javax.swing.JMenuItem();
        jListadoMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos ");

        jAgregarAlumno.setText("Agregar Alumno");
        jAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jAgregarAlumno);

        jBuscarAlumno.setText("Buscar Alumno");
        jBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jBuscarAlumno);

        jModificarAlumno.setText("Modificar Alumno");
        jModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jModificarAlumno);

        jAltaLogica.setText("Alta Logica");
        jAltaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaLogicaActionPerformed(evt);
            }
        });
        jMenu1.add(jAltaLogica);

        jBajaLogica.setText("Baja Logica");
        jBajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBajaLogicaActionPerformed(evt);
            }
        });
        jMenu1.add(jBajaLogica);

        jListadoAlumnos.setText("Listado Alumnos");
        jListadoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListadoAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jListadoAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        jAgregarMaterias.setText("Agregar Materias");
        jAgregarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jAgregarMaterias);

        jBuscarMaterias.setText("Buscar Materias");
        jBuscarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jBuscarMaterias);

        jModificarMaterias.setText("Modificar Materias");
        jModificarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jModificarMaterias);

        jMAltaLogica.setText("Alta Logica");
        jMAltaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAltaLogicaActionPerformed(evt);
            }
        });
        jMenu2.add(jMAltaLogica);

        jMBajaLogica.setText("Baja Logica");
        jMBajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBajaLogicaActionPerformed(evt);
            }
        });
        jMenu2.add(jMBajaLogica);

        jListadoMaterias.setText("Listado Materias");
        jListadoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListadoMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jListadoMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenu3.add(jSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListadoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListadoAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListadoAlumnosActionPerformed

    private void jAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgregarAlumnoActionPerformed

    private void jBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarAlumnoActionPerformed

    private void jModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jModificarAlumnoActionPerformed

    private void jAltaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAltaLogicaActionPerformed

    private void jBajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBajaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBajaLogicaActionPerformed

    private void jAgregarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgregarMateriasActionPerformed

    private void jBuscarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarMateriasActionPerformed

    private void jMAltaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAltaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAltaLogicaActionPerformed

    private void jModificarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jModificarMateriasActionPerformed

    private void jMBajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBajaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMBajaLogicaActionPerformed

    private void jListadoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListadoMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListadoMateriasActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAgregarAlumno;
    private javax.swing.JMenuItem jAgregarMaterias;
    private javax.swing.JMenuItem jAltaLogica;
    private javax.swing.JMenuItem jBajaLogica;
    private javax.swing.JMenuItem jBuscarAlumno;
    private javax.swing.JMenuItem jBuscarMaterias;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jListadoAlumnos;
    private javax.swing.JMenuItem jListadoMaterias;
    private javax.swing.JMenuItem jMAltaLogica;
    private javax.swing.JMenuItem jMBajaLogica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jModificarAlumno;
    private javax.swing.JMenuItem jModificarMaterias;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
