/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import vista.frmAlumno;
import Vista.frmMateria;
import Vista.frmInscripciones;

/**
 *
 * @author Lulim
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jFormularioAlumnos = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jFormularioMaterias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jFormularioInscripcion = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jNotasEditar = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuListado = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumnos");

        jFormularioAlumnos.setText("Formulario Alumnos");
        jFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormularioAlumnosActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jFormularioAlumnos);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materias");

        jFormularioMaterias.setText("Formulario Materias ");
        jFormularioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormularioMateriasActionPerformed(evt);
            }
        });
        jMenuMateria.add(jFormularioMaterias);

        jMenuBar1.add(jMenuMateria);

        jMenu1.setText("Inscripciones");

        jFormularioInscripcion.setText("Formulario Inscripcion ");
        jFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormularioInscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(jFormularioInscripcion);

        jMenuBar1.add(jMenu1);

        jMenuConsulta.setText("Carga de Notas");

        jNotasEditar.setText("Manejo de Notas");
        jNotasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotasEditarActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jNotasEditar);

        jMenuBar1.add(jMenuConsulta);

        jMenuListar.setText("Listar Inscripciones");

        jMenuListado.setText("jMenuItem1");
        jMenuListar.add(jMenuListado);

        jMenuBar1.add(jMenuListar);

        jMenuSalir.setText("Salir");

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jFormularioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormularioMateriasActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        frmMateria materia = new frmMateria();
        materia.setVisible(true);
        jEscritorio.add(materia);
        int x = (jEscritorio.getWidth() - materia.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - materia.getHeight()) / 2;
        materia.setLocation(x, y);
        jEscritorio.moveToFront(materia);
    }//GEN-LAST:event_jFormularioMateriasActionPerformed

    private void jFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormularioAlumnosActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        frmAlumno alumno = new frmAlumno();
        alumno.setVisible(true);
        jEscritorio.add(alumno);
        int x = (jEscritorio.getWidth() - alumno.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - alumno.getHeight()) / 2;
        alumno.setLocation(x, y);
        jEscritorio.moveToFront(alumno);
    }//GEN-LAST:event_jFormularioAlumnosActionPerformed

    private void jFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormularioInscripcionActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        frmInscripciones inscripciones = new frmInscripciones();
        inscripciones.setVisible(true);
        jEscritorio.add(inscripciones);
        int x = (jEscritorio.getWidth() - inscripciones.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - inscripciones.getHeight()) / 2;
        inscripciones.setLocation(x, y);
        jEscritorio.moveToFront(inscripciones);
    }//GEN-LAST:event_jFormularioInscripcionActionPerformed

    private void jNotasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotasEditarActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        frmCargaNotas vn = new frmCargaNotas();
        vn.setVisible(true);
        jEscritorio.add(vn);
        int x = (jEscritorio.getWidth() - vn.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - vn.getHeight()) / 2;
        vn.setLocation(x, y);
        jEscritorio.moveToFront(vn);
    }//GEN-LAST:event_jNotasEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuItem jFormularioAlumnos;
    private javax.swing.JMenuItem jFormularioInscripcion;
    private javax.swing.JMenuItem jFormularioMaterias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuListado;
    private javax.swing.JMenu jMenuListar;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jNotasEditar;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
